do (Backbone, Marionette, Jig, $, _) ->
  Jig.extendApp (App) ->
    class App.LayoutView extends Marionette.LayoutView
      refreshModel: App.viewHelpers.refreshModel
      updateModel : App.viewHelpers.updateModel

      constructor: (args...) ->
        App.viewHelpers.beforeConstructed.call @, args...
        super args...
        App.viewHelpers.afterConstructed.call @, args...

      delegateEvents: (args...) ->
        super args...
        App.viewHelpers.bindCustomEntityEvents.call @, args...

      undelegateEvents: (args...) ->
        super args...
        App.viewHelpers.unbindCustomEntityEvents.call @, args...

      mixinTemplateHelpers: (target) ->
        _.extend target, App.templateHelpers
        super target
